# Generated by Django 5.2.17 on 2026-10-06 06:37

import apps.converter.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('source_format', models.CharField(db_index=True, max_length=32)),
                ('target_format', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('input_file', models.FileField(upload_to=apps.converter.models.upload_to_input)),
                ('output_file', models.FileField(blank=True, upload_to=apps.converter.models.upload_to_output)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'expires_at'], name='converter_c_status_23540b_idx'), models.Index(fields=['source_format', 'target_format'], name='converter_c_source__4ce2cf_idx')],
            },
        ),
    ]
