# Generated by Django 5.2.17 on 2026-10-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='owner_session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['owner_session_key', 'created_at'], name='converter_c_owner_s_918d64_idx'),
        ),
    ]
