# Generated by Django 5.2.17 on 2026-10-06 13:19

import apps.converter.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_owner_session_and_history_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('target_format', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='pending', max_length=16)),
                ('zip_file', models.FileField(blank=True, upload_to=apps.converter.models.upload_to_batch_zip)),
                ('error_message', models.TextField(blank=True)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'expires_at'], name='converter_c_status_ede547_idx'), models.Index(fields=['owner_session_key', 'created_at'], name='converter_c_owner_s_7a2841_idx')],
            },
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='converter.conversionbatch'),
        ),
    ]
